from ricercar.website.models.bibliotheque import Bibliotheque
from ricercar.website.models.localisation import Localisation
from ricercar.website.models.role import Role
from ricercar.website.models.personne import Personne
from ricercar.website.models.genre_musical_detaille import GenreMusicalDetaille
from ricercar.website.models.catalogue import Catalogue
from ricercar.website.models.piece import Piece
from ricercar.website.models.recueil import Recueil
from ricercar.website.models.projet import Projet
from ricercar.website.models.genre_musical_normalise import GenreMusicalNormalise
from ricercar.website.models.blog import Article
from ricercar.website.models.voix import Voix
from ricercar.website.models.exemplaire import Exemplaire
